# installs dependenices, builds the site, and pushes the output to the gh-pages branch
# cd to website/13F.grandfleet.eu.org
# pelican content -o output -s publishconf.py
# publish output to gh-pages branch
# 
name: Publish to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build site
      run: |
        cd website/13F.grandfleet.eu.org
        pelican content -o output -s publishconf.py
        sed -i '6i <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2479144310234386" crossorigin="anonymous"></script>' output/*.html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.MAIN_REPO_TOKEN }}
        BRANCH: gh-pages
        FOLDER: website/13F.grandfleet.eu.org/output
